/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleSetChoiceExtensibility"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/48-real-life-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_UserIdentifier_H_
#define	_UserIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UserIdentifier_PR {
	UserIdentifier_PR_NOTHING,	/* No components present */
	UserIdentifier_PR_phoneNumber
} UserIdentifier_PR;

/* UserIdentifier */
typedef struct UserIdentifier {
	UserIdentifier_PR present;
	union UserIdentifier_u {
		IA5String_t	 phoneNumber;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UserIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserIdentifier;

#ifdef __cplusplus
}
#endif

#endif	/* _UserIdentifier_H_ */
#include <asn_internal.h>
