/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleRecursion"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/43-recursion-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "Test-structure-1.h"

static asn_TYPE_member_t asn_MBR_t_member1_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Test_structure_1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_t_member1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_t_member1_specs_2 = {
	sizeof(struct t_member1),
	offsetof(struct t_member1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_t_member1_2 = {
	"t-member1",
	"t-member1",
	&asn_OP_SET_OF,
	asn_DEF_t_member1_tags_2,
	sizeof(asn_DEF_t_member1_tags_2)
		/sizeof(asn_DEF_t_member1_tags_2[0]), /* 1 */
	asn_DEF_t_member1_tags_2,	/* Same as above */
	sizeof(asn_DEF_t_member1_tags_2)
		/sizeof(asn_DEF_t_member1_tags_2[0]), /* 1 */
	{ 0, 0, SET_OF_constraint },
	asn_MBR_t_member1_2,
	1,	/* Single element */
	&asn_SPC_t_member1_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_t_member2_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Test_structure_1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_t_member2_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_t_member2_specs_4 = {
	sizeof(struct t_member2),
	offsetof(struct t_member2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_t_member2_4 = {
	"t-member2",
	"t-member2",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_t_member2_tags_4,
	sizeof(asn_DEF_t_member2_tags_4)
		/sizeof(asn_DEF_t_member2_tags_4[0]), /* 1 */
	asn_DEF_t_member2_tags_4,	/* Same as above */
	sizeof(asn_DEF_t_member2_tags_4)
		/sizeof(asn_DEF_t_member2_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_t_member2_4,
	1,	/* Single element */
	&asn_SPC_t_member2_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Test_structure_1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Test_structure_1, t_member1),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_t_member1_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"t-member1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Test_structure_1, t_member2),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_t_member2_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"t-member2"
		},
	{ ATF_POINTER, 1, offsetof(struct Test_structure_1, t_member3),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Test_structure_1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"t-member3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Test_structure_1, t_member4),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"t-member4"
		},
};
static const int asn_MAP_Test_structure_1_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_Test_structure_1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Test_structure_1_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, 0, 0 }, /* t-member4 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* t-member2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 }, /* t-member3 */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 0, 0, 0 } /* t-member1 */
};
asn_SEQUENCE_specifics_t asn_SPC_Test_structure_1_specs_1 = {
	sizeof(struct Test_structure_1),
	offsetof(struct Test_structure_1, _asn_ctx),
	asn_MAP_Test_structure_1_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Test_structure_1_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Test_structure_1 = {
	"Test-structure-1",
	"Test-structure-1",
	&asn_OP_SEQUENCE,
	asn_DEF_Test_structure_1_tags_1,
	sizeof(asn_DEF_Test_structure_1_tags_1)
		/sizeof(asn_DEF_Test_structure_1_tags_1[0]), /* 1 */
	asn_DEF_Test_structure_1_tags_1,	/* Same as above */
	sizeof(asn_DEF_Test_structure_1_tags_1)
		/sizeof(asn_DEF_Test_structure_1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Test_structure_1_1,
	4,	/* Elements count */
	&asn_SPC_Test_structure_1_specs_1	/* Additional specs */
};

