/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleRecursion"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/43-recursion-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "Test-structure-2.h"

asn_TYPE_member_t asn_MBR_Test_structure_2_1[] = {
	{ ATF_POINTER, 1, offsetof(struct Test_structure_2, m1),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_Test_structure_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m1"
		},
};
static const ber_tlv_tag_t asn_DEF_Test_structure_2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Test_structure_2_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 0, 0, 0 } /* m1 */
};
static const uint8_t asn_MAP_Test_structure_2_mmap_1[(1 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(0 << 7)
};
asn_SET_specifics_t asn_SPC_Test_structure_2_specs_1 = {
	sizeof(struct Test_structure_2),
	offsetof(struct Test_structure_2, _asn_ctx),
	offsetof(struct Test_structure_2, _presence_map),
	asn_MAP_Test_structure_2_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_Test_structure_2_tag2el_1,	/* Same as above */
	1,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(const unsigned int *)asn_MAP_Test_structure_2_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_Test_structure_2 = {
	"Test-structure-2",
	"Test-structure-2",
	&asn_OP_SET,
	asn_DEF_Test_structure_2_tags_1,
	sizeof(asn_DEF_Test_structure_2_tags_1)
		/sizeof(asn_DEF_Test_structure_2_tags_1[0]), /* 1 */
	asn_DEF_Test_structure_2_tags_1,	/* Same as above */
	sizeof(asn_DEF_Test_structure_2_tags_1)
		/sizeof(asn_DEF_Test_structure_2_tags_1[0]), /* 1 */
	{ 0, 0, SET_constraint },
	asn_MBR_Test_structure_2_1,
	1,	/* Elements count */
	&asn_SPC_Test_structure_2_specs_1	/* Additional specs */
};

