/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMultipleTags"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/65-multi-tag-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_T2_H_
#define	_T2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "T3.h"

#ifdef __cplusplus
extern "C" {
#endif

/* T2 */
typedef T3_t	 T2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T2;
asn_struct_free_f T2_free;
asn_struct_print_f T2_print;
asn_constr_check_f T2_constraint;
ber_type_decoder_f T2_decode_ber;
der_type_encoder_f T2_encode_der;
xer_type_decoder_f T2_decode_xer;
xer_type_encoder_f T2_encode_xer;
oer_type_decoder_f T2_decode_oer;
oer_type_encoder_f T2_encode_oer;
per_type_decoder_f T2_decode_uper;
per_type_encoder_f T2_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _T2_H_ */
#include <asn_internal.h>
