/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMultipleTags"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/65-multi-tag-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_T5_H_
#define	_T5_H_


#include <asn_application.h>

/* Including external dependencies */
#include "T6.h"

#ifdef __cplusplus
extern "C" {
#endif

/* T5 */
typedef T6_t	 T5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T5;
asn_struct_free_f T5_free;
asn_struct_print_f T5_print;
asn_constr_check_f T5_constraint;
ber_type_decoder_f T5_decode_ber;
der_type_encoder_f T5_encode_der;
xer_type_decoder_f T5_decode_xer;
xer_type_encoder_f T5_encode_xer;
oer_type_decoder_f T5_decode_oer;
oer_type_encoder_f T5_encode_oer;
per_type_decoder_f T5_decode_uper;
per_type_encoder_f T5_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _T5_H_ */
#include <asn_internal.h>
