/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMultipleTags"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/65-multi-tag-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "T6.h"

/*
 * This type is implemented using NativeReal,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_T6_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
asn_TYPE_descriptor_t asn_DEF_T6 = {
	"T6",
	"T6",
	&asn_OP_NativeReal,
	asn_DEF_T6_tags_1,
	sizeof(asn_DEF_T6_tags_1)
		/sizeof(asn_DEF_T6_tags_1[0]), /* 1 */
	asn_DEF_T6_tags_1,	/* Same as above */
	sizeof(asn_DEF_T6_tags_1)
		/sizeof(asn_DEF_T6_tags_1[0]), /* 1 */
	{ 0, 0, NativeReal_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

