/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMultipleTags"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/65-multi-tag-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "Ts.h"

asn_TYPE_member_t asn_MBR_Ts_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ts, m1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_T2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m1"
		},
	{ ATF_POINTER, 1, offsetof(struct Ts, m2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_T3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ts, m3),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_T3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m3"
		},
};
static const int asn_MAP_Ts_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_Ts_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (123 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Ts_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* m1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* m2 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* m3 */
};
asn_SEQUENCE_specifics_t asn_SPC_Ts_specs_1 = {
	sizeof(struct Ts),
	offsetof(struct Ts, _asn_ctx),
	asn_MAP_Ts_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Ts_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Ts = {
	"Ts",
	"Ts",
	&asn_OP_SEQUENCE,
	asn_DEF_Ts_tags_1,
	sizeof(asn_DEF_Ts_tags_1)
		/sizeof(asn_DEF_Ts_tags_1[0]) - 1, /* 1 */
	asn_DEF_Ts_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ts_tags_1)
		/sizeof(asn_DEF_Ts_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ts_1,
	3,	/* Elements count */
	&asn_SPC_Ts_specs_1	/* Additional specs */
};

