/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Programming;
extern struct asn_TYPE_descriptor_s asn_DEF_SeqWithMandatory;
extern struct asn_TYPE_descriptor_s asn_DEF_SeqWithOptional;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ModuleTestSequenceSimple in /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/32-sequence-of-OK.asn1 */
	&asn_DEF_Programming,	
	&asn_DEF_SeqWithMandatory,	
	&asn_DEF_SeqWithOptional,	
	0
};

