/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModulePERStrings"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/119-per-strings-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -fwide-types -gen-PER`
 */

#ifndef	_PDU_H_
#define	_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <VisibleString.h>
#include <PrintableString.h>
#include <NumericString.h>
#include <UTF8String.h>
#include <BMPString.h>
#include <UniversalString.h>
#include <REAL.h>
#include <OBJECT_IDENTIFIER.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDU;

/* PDU */
typedef struct PDU {
	struct many {
		A_SEQUENCE_OF(struct PDU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *many;
	IA5String_t	*ia5	/* OPTIONAL */;
	IA5String_t	*ia5_c	/* OPTIONAL */;
	IA5String_t	*ia5_ce	/* OPTIONAL */;
	IA5String_t	*ia5_ir	/* OPTIONAL */;
	VisibleString_t	*vs	/* OPTIONAL */;
	VisibleString_t	*vs_c	/* OPTIONAL */;
	VisibleString_t	*vs_ce	/* OPTIONAL */;
	VisibleString_t	*vs_ir	/* OPTIONAL */;
	PrintableString_t	*pr	/* OPTIONAL */;
	PrintableString_t	*pr_c	/* OPTIONAL */;
	PrintableString_t	*pr_ir	/* OPTIONAL */;
	NumericString_t	*ns	/* OPTIONAL */;
	NumericString_t	*ns_c	/* OPTIONAL */;
	NumericString_t	*ns_ce	/* OPTIONAL */;
	NumericString_t	*ns_ir	/* OPTIONAL */;
	UTF8String_t	*ut_c	/* OPTIONAL */;
	UTF8String_t	*ut_ce	/* OPTIONAL */;
	UTF8String_t	*ut_ir	/* OPTIONAL */;
	BMPString_t	*bm	/* OPTIONAL */;
	BMPString_t	*bm_c	/* OPTIONAL */;
	BMPString_t	*bm_cs	/* OPTIONAL */;
	BMPString_t	*bm_ce	/* OPTIONAL */;
	BMPString_t	*bm_ir	/* OPTIONAL */;
	UniversalString_t	*us	/* OPTIONAL */;
	UniversalString_t	*us_c	/* OPTIONAL */;
	UniversalString_t	*us_cs	/* OPTIONAL */;
	UniversalString_t	*us_ce	/* OPTIONAL */;
	UniversalString_t	*us_ir	/* OPTIONAL */;
	REAL_t	*real	/* OPTIONAL */;
	OBJECT_IDENTIFIER_t	*oid	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDU;
extern asn_SEQUENCE_specifics_t asn_SPC_PDU_specs_1;
extern asn_TYPE_member_t asn_MBR_PDU_1[31];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDU.h"

#endif	/* _PDU_H_ */
#include <asn_internal.h>
