/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModulePERExtensions"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/126-per-extensions-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -gen-PER`
 */

#include "PDU-2.h"

static asn_oer_constraints_t asn_OER_type_PDU_2_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_PDU_2_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_PDU_2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDU_2, choice.main),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"main"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDU_2, choice.ext1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDU_2, choice.ext0),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext0"
		},
};
static const unsigned asn_MAP_PDU_2_to_canonical_1[] = { 0, 2, 1 };
static const unsigned asn_MAP_PDU_2_from_canonical_1[] = { 0, 2, 1 };
static const asn_TYPE_tag2member_t asn_MAP_PDU_2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* ext0 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ext1 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 } /* main */
};
asn_CHOICE_specifics_t asn_SPC_PDU_2_specs_1 = {
	sizeof(struct PDU_2),
	offsetof(struct PDU_2, _asn_ctx),
	offsetof(struct PDU_2, present),
	sizeof(((struct PDU_2 *)0)->present),
	asn_MAP_PDU_2_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_PDU_2_to_canonical_1,
	asn_MAP_PDU_2_from_canonical_1,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PDU_2 = {
	"PDU-2",
	"PDU-2",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_PDU_2_constr_1, &asn_PER_type_PDU_2_constr_1, CHOICE_constraint },
	asn_MBR_PDU_2_1,
	3,	/* Elements count */
	&asn_SPC_PDU_2_specs_1	/* Additional specs */
};

