/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModulePERExtensions"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/126-per-extensions-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -gen-PER`
 */

#ifndef	_PDU_2_H_
#define	_PDU_2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDU_2_PR {
	PDU_2_PR_NOTHING,	/* No components present */
	PDU_2_PR_main,
	/* Extensions may appear below */
	PDU_2_PR_ext1,
	PDU_2_PR_ext0
} PDU_2_PR;

/* PDU-2 */
typedef struct PDU_2 {
	PDU_2_PR present;
	union PDU_2_u {
		long	 main;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		long	 ext1;
		long	 ext0;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDU_2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDU_2;
extern asn_CHOICE_specifics_t asn_SPC_PDU_2_specs_1;
extern asn_TYPE_member_t asn_MBR_PDU_2_1[3];
extern asn_per_constraints_t asn_PER_type_PDU_2_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PDU_2_H_ */
#include <asn_internal.h>
