/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModulePERExtensions"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/126-per-extensions-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -gen-PER`
 */

#include "Singleton.h"

static int asn_DFL_2_cmp(const void *sptr) {
	static const uint8_t defv[] = "z";
	const IA5String_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	if(st->size == (sizeof(defv) - 1)
	&& memcmp(st->buf, &defv, sizeof(defv) - 1) == 0)
		return 0;
	return 1;
}
static int asn_DFL_2_set(void **sptr) {
	static const uint8_t defv[] = "z";
	IA5String_t *st = *sptr;
	uint8_t *nstr = MALLOC(sizeof(defv));
	
	if(!nstr) return -1;
	memcpy(nstr, defv, sizeof(defv));
	
	if(st) {
		FREEMEM(st->buf);
	} else {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) { FREEMEM(nstr); return -1; }
	}
	st->buf = nstr;
	st->size = sizeof(defv) - 1;
	
	return 0;
}
asn_TYPE_member_t asn_MBR_Singleton_1[] = {
	{ ATF_POINTER, 1, offsetof(struct Singleton, opt_z),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp,	/* Compare DEFAULT "z" */
		&asn_DFL_2_set,	/* Set DEFAULT "z" */
		"opt-z"
		},
};
static const int asn_MAP_Singleton_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_Singleton_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Singleton_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* opt-z */
};
asn_SEQUENCE_specifics_t asn_SPC_Singleton_specs_1 = {
	sizeof(struct Singleton),
	offsetof(struct Singleton, _asn_ctx),
	asn_MAP_Singleton_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_Singleton_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Singleton = {
	"Singleton",
	"Singleton",
	&asn_OP_SEQUENCE,
	asn_DEF_Singleton_tags_1,
	sizeof(asn_DEF_Singleton_tags_1)
		/sizeof(asn_DEF_Singleton_tags_1[0]), /* 1 */
	asn_DEF_Singleton_tags_1,	/* Same as above */
	sizeof(asn_DEF_Singleton_tags_1)
		/sizeof(asn_DEF_Singleton_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Singleton_1,
	1,	/* Elements count */
	&asn_SPC_Singleton_specs_1	/* Additional specs */
};

