/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestDerSetSequenceValues"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/148-der-default-set-sequence-values-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_DefaultSet_H_
#define	_DefaultSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum DefaultSet_PR {
	DefaultSet_PR_aBool,	/* Member aBool is present */
	DefaultSet_PR_anInteger,	/* Member anInteger is present */
} DefaultSet_PR;

/* DefaultSet */
typedef struct DefaultSet {
	BOOLEAN_t	 aBool	/* DEFAULT FALSE */;
	long	*anInteger	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pDefaultSet, DefaultSet_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefaultSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefaultSet;

#ifdef __cplusplus
}
#endif

#endif	/* _DefaultSet_H_ */
#include <asn_internal.h>
