/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestDerSetSequenceValues"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/148-der-default-set-sequence-values-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "DefaultSet.h"

static int asn_DFL_2_cmp_0(const void *sptr) {
	const BOOLEAN_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_2_set_0(void **sptr) {
	BOOLEAN_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
static asn_TYPE_member_t asn_MBR_DefaultSet_1[] = {
	{ ATF_NOFLAGS, 2, offsetof(struct DefaultSet, aBool),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_2_set_0,	/* Set DEFAULT 0 */
		"aBool"
		},
	{ ATF_POINTER, 1, offsetof(struct DefaultSet, anInteger),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"anInteger"
		},
};
static const ber_tlv_tag_t asn_DEF_DefaultSet_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DefaultSet_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aBool */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* anInteger */
};
static const uint8_t asn_MAP_DefaultSet_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(0 << 7) | (0 << 6)
};
static 
asn_SET_specifics_t asn_SPC_DefaultSet_specs_1 = {
	sizeof(struct DefaultSet),
	offsetof(struct DefaultSet, _asn_ctx),
	offsetof(struct DefaultSet, _presence_map),
	asn_MAP_DefaultSet_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_DefaultSet_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(const unsigned int *)asn_MAP_DefaultSet_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_DefaultSet = {
	"DefaultSet",
	"DefaultSet",
	&asn_OP_SET,
	asn_DEF_DefaultSet_tags_1,
	sizeof(asn_DEF_DefaultSet_tags_1)
		/sizeof(asn_DEF_DefaultSet_tags_1[0]), /* 1 */
	asn_DEF_DefaultSet_tags_1,	/* Same as above */
	sizeof(asn_DEF_DefaultSet_tags_1)
		/sizeof(asn_DEF_DefaultSet_tags_1[0]), /* 1 */
	{ 0, 0, SET_constraint },
	asn_MBR_DefaultSet_1,
	2,	/* Elements count */
	&asn_SPC_DefaultSet_specs_1	/* Additional specs */
};

