/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestDerSetSequenceValues"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/148-der-default-set-sequence-values-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_DefaultSequence_H_
#define	_DefaultSequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefaultSequence */
typedef struct DefaultSequence {
	BOOLEAN_t	 aBool	/* DEFAULT FALSE */;
	long	*anInteger	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefaultSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefaultSequence;

#ifdef __cplusplus
}
#endif

#endif	/* _DefaultSequence_H_ */
#include <asn_internal.h>
