/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_DefaultSequence;
extern struct asn_TYPE_descriptor_s asn_DEF_DefaultSet;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ModuleTestDerSetSequenceValues in /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/148-der-default-set-sequence-values-OK.asn1 */
	&asn_DEF_DefaultSequence,	
	&asn_DEF_DefaultSet,	
	0
};

