/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_T1;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ModuleTestTags3 in /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/22-tags-OK.asn1 */
	&asn_DEF_T1,	
	0
};

