/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestTags3"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/22-tags-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -fwide-types`
 */

#ifndef	_T1_H_
#define	_T1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <UTF8String.h>
#include <IA5String.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum b_PR {
	b_PR_NOTHING,	/* No components present */
	b_PR_i,
	b_PR_n
} b_PR;

/* T1 */
typedef struct T1 {
	INTEGER_t	 a;
	struct b {
		b_PR present;
		union T1__b_u {
			INTEGER_t	 i;
			IA5String_t	 n;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} b;
	UTF8String_t	 c;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T1;

#ifdef __cplusplus
}
#endif

#endif	/* _T1_H_ */
#include <asn_internal.h>
