/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Test"
 * 	found in "test.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -fnative-types -flink-skeletons`
 */

#ifndef	_Real64_H_
#define	_Real64_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeReal.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Real64 */
typedef double	 Real64_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Real64_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Real64;
asn_struct_free_f Real64_free;
asn_struct_print_f Real64_print;
asn_constr_check_f Real64_constraint;
ber_type_decoder_f Real64_decode_ber;
der_type_encoder_f Real64_encode_der;
xer_type_decoder_f Real64_decode_xer;
xer_type_encoder_f Real64_encode_xer;
oer_type_decoder_f Real64_decode_oer;
oer_type_encoder_f Real64_encode_oer;
per_type_decoder_f Real64_decode_uper;
per_type_encoder_f Real64_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Real64_H_ */
#include <asn_internal.h>
