/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestANY"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/60-any-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_T3_H_
#define	_T3_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* T3 */
typedef struct T3 {
	ANY_t	 any1;
	ANY_t	 any2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T3;

#ifdef __cplusplus
}
#endif

#endif	/* _T3_H_ */
#include <asn_internal.h>
