/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModulePERConstraints"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/133-per-constraints-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -gen-PER`
 */

#include "T.h"

static int
nothing_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if((value >= 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_nothing_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if((value >= 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_second_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value <= 10)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_third_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -10)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_nothing_constr_3 CC_NOTUSED = {
	{ 0, 1 }	/* (5..MAX) */,
	-1};
static asn_per_constraints_t asn_PER_type_nothing_constr_3 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  5,  0 }	/* (5..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_nothing_constr_3 CC_NOTUSED = {
	{ 0, 1 }	/* (5..MAX) */,
	-1};
static asn_per_constraints_t asn_PER_memb_nothing_constr_3 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  5,  0 }	/* (5..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_first_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_first_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_second_constr_4 CC_NOTUSED = {
	{ 0, 0 }	/* (MIN..10) */,
	-1};
static asn_per_constraints_t asn_PER_memb_second_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }	/* (MIN..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_third_constr_6 CC_NOTUSED = {
	{ 0, 0 }	/* (-10..MAX) */,
	-1};
static asn_per_constraints_t asn_PER_memb_third_constr_6 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1, -10,  0 }	/* (-10..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_T_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_T_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_nothing_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_nothing_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nothing_3 = {
	"nothing",
	"nothing",
	&asn_OP_NativeInteger,
	asn_DEF_nothing_tags_3,
	sizeof(asn_DEF_nothing_tags_3)
		/sizeof(asn_DEF_nothing_tags_3[0]) - 1, /* 1 */
	asn_DEF_nothing_tags_3,	/* Same as above */
	sizeof(asn_DEF_nothing_tags_3)
		/sizeof(asn_DEF_nothing_tags_3[0]), /* 2 */
	{ &asn_OER_type_nothing_constr_3, &asn_PER_type_nothing_constr_3, nothing_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_nothing_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_first_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct first, choice.nothing),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_nothing_3,
		0,
		{ &asn_OER_memb_nothing_constr_3, &asn_PER_memb_nothing_constr_3,  memb_nothing_constraint_2 },
		0, 0, /* No default value */
		"nothing"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_first_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* nothing */
};
static asn_CHOICE_specifics_t asn_SPC_first_specs_2 = {
	sizeof(struct first),
	offsetof(struct first, _asn_ctx),
	offsetof(struct first, present),
	sizeof(((struct first *)0)->present),
	asn_MAP_first_tag2el_2,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_first_2 = {
	"first",
	"first",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_first_constr_2, &asn_PER_type_first_constr_2, CHOICE_constraint },
	asn_MBR_first_2,
	1,	/* Elements count */
	&asn_SPC_first_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_T_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct T, choice.first),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_first_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"first"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct T, choice.second),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_second_constr_4, &asn_PER_memb_second_constr_4,  memb_second_constraint_1 },
		0, 0, /* No default value */
		"second"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct T, choice.third),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_third_constr_6, &asn_PER_memb_third_constr_6,  memb_third_constraint_1 },
		0, 0, /* No default value */
		"third"
		},
};
static const unsigned asn_MAP_T_to_canonical_1[] = { 1, 0, 2 };
static const unsigned asn_MAP_T_from_canonical_1[] = { 1, 0, 2 };
static const asn_TYPE_tag2member_t asn_MAP_T_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* second */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* third */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 } /* first */
};
static asn_CHOICE_specifics_t asn_SPC_T_specs_1 = {
	sizeof(struct T),
	offsetof(struct T, _asn_ctx),
	offsetof(struct T, present),
	sizeof(((struct T *)0)->present),
	asn_MAP_T_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_T_to_canonical_1,
	asn_MAP_T_from_canonical_1,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_T = {
	"T",
	"T",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_T_constr_1, &asn_PER_type_T_constr_1, CHOICE_constraint },
	asn_MBR_T_1,
	3,	/* Elements count */
	&asn_SPC_T_specs_1	/* Additional specs */
};

