/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestCircularReferences"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/73-circular-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_EnumType_H_
#define	_EnumType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnumType {
	EnumType_one	= 0,
	EnumType_two	= 1
} e_EnumType;

/* EnumType */
typedef long	 EnumType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EnumType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EnumType;
extern const asn_INTEGER_specifics_t asn_SPC_EnumType_specs_1;
asn_struct_free_f EnumType_free;
asn_struct_print_f EnumType_print;
asn_constr_check_f EnumType_constraint;
ber_type_decoder_f EnumType_decode_ber;
der_type_encoder_f EnumType_encode_der;
xer_type_decoder_f EnumType_decode_xer;
xer_type_encoder_f EnumType_encode_xer;
oer_type_decoder_f EnumType_decode_oer;
oer_type_encoder_f EnumType_encode_oer;
per_type_decoder_f EnumType_decode_uper;
per_type_encoder_f EnumType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EnumType_H_ */
#include <asn_internal.h>
