/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestCircularReferences"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/73-circular-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_EpytRef_H_
#define	_EpytRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Epyt.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EpytRef */
typedef Epyt_t	 EpytRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EpytRef;
asn_struct_free_f EpytRef_free;
asn_struct_print_f EpytRef_print;
asn_constr_check_f EpytRef_constraint;
ber_type_decoder_f EpytRef_decode_ber;
der_type_encoder_f EpytRef_encode_der;
xer_type_decoder_f EpytRef_decode_xer;
xer_type_encoder_f EpytRef_encode_xer;
oer_type_decoder_f EpytRef_decode_oer;
oer_type_encoder_f EpytRef_encode_oer;
per_type_decoder_f EpytRef_decode_uper;
per_type_encoder_f EpytRef_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EpytRef_H_ */
#include <asn_internal.h>
