/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSameNames"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/72-same-names-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -fcompound-names`
 */

#include "Type1.h"

static asn_oer_constraints_t asn_OER_type_one_name_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_one_name_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_another_name_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type1__one_name__another_name, a),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"a"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Type1__one_name__another_name, b),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b"
		},
};
static const ber_tlv_tag_t asn_DEF_another_name_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_another_name_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* a */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* b */
};
static asn_SEQUENCE_specifics_t asn_SPC_another_name_specs_3 = {
	sizeof(struct Type1__one_name__another_name),
	offsetof(struct Type1__one_name__another_name, _asn_ctx),
	asn_MAP_another_name_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_another_name_3 = {
	"another-name",
	"another-name",
	&asn_OP_SEQUENCE,
	asn_DEF_another_name_tags_3,
	sizeof(asn_DEF_another_name_tags_3)
		/sizeof(asn_DEF_another_name_tags_3[0]), /* 1 */
	asn_DEF_another_name_tags_3,	/* Same as above */
	sizeof(asn_DEF_another_name_tags_3)
		/sizeof(asn_DEF_another_name_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_another_name_3,
	2,	/* Elements count */
	&asn_SPC_another_name_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_one_name_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type1__one_name, choice.another_name),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_another_name_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"another-name"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_one_name_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* another-name */
};
static asn_CHOICE_specifics_t asn_SPC_one_name_specs_2 = {
	sizeof(struct Type1__one_name),
	offsetof(struct Type1__one_name, _asn_ctx),
	offsetof(struct Type1__one_name, present),
	sizeof(((struct Type1__one_name *)0)->present),
	asn_MAP_one_name_tag2el_2,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_one_name_2 = {
	"one-name",
	"one-name",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_one_name_constr_2, &asn_PER_type_one_name_constr_2, CHOICE_constraint },
	asn_MBR_one_name_2,
	1,	/* Elements count */
	&asn_SPC_one_name_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Type1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type1, one_name),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_one_name_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"one-name"
		},
};
static const ber_tlv_tag_t asn_DEF_Type1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Type1_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* another-name */
};
asn_SEQUENCE_specifics_t asn_SPC_Type1_specs_1 = {
	sizeof(struct Type1),
	offsetof(struct Type1, _asn_ctx),
	asn_MAP_Type1_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Type1 = {
	"Type1",
	"Type1",
	&asn_OP_SEQUENCE,
	asn_DEF_Type1_tags_1,
	sizeof(asn_DEF_Type1_tags_1)
		/sizeof(asn_DEF_Type1_tags_1[0]), /* 1 */
	asn_DEF_Type1_tags_1,	/* Same as above */
	sizeof(asn_DEF_Type1_tags_1)
		/sizeof(asn_DEF_Type1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Type1_1,
	1,	/* Elements count */
	&asn_SPC_Type1_specs_1	/* Additional specs */
};

