/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSameNames"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/72-same-names-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -fcompound-names`
 */

#include "Type2.h"

static int
memb_a_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_a_constraint_8(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_a_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_a_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_a_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_a_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_Type2_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Type2_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_another_name_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type2__one_name__another_name, a),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_a_constr_4, &asn_PER_memb_a_constr_4,  memb_a_constraint_3 },
		0, 0, /* No default value */
		"a"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Type2__one_name__another_name, b),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b"
		},
};
static const ber_tlv_tag_t asn_DEF_another_name_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_another_name_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* b */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 0 } /* a */
};
static asn_SEQUENCE_specifics_t asn_SPC_another_name_specs_3 = {
	sizeof(struct Type2__one_name__another_name),
	offsetof(struct Type2__one_name__another_name, _asn_ctx),
	asn_MAP_another_name_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_another_name_3 = {
	"another-name",
	"another-name",
	&asn_OP_SEQUENCE,
	asn_DEF_another_name_tags_3,
	sizeof(asn_DEF_another_name_tags_3)
		/sizeof(asn_DEF_another_name_tags_3[0]), /* 1 */
	asn_DEF_another_name_tags_3,	/* Same as above */
	sizeof(asn_DEF_another_name_tags_3)
		/sizeof(asn_DEF_another_name_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_another_name_3,
	2,	/* Elements count */
	&asn_SPC_another_name_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_one_name_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type2__one_name, another_name),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_another_name_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"another-name"
		},
};
static const ber_tlv_tag_t asn_DEF_one_name_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_one_name_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* another-name */
};
static asn_SEQUENCE_specifics_t asn_SPC_one_name_specs_2 = {
	sizeof(struct Type2__one_name),
	offsetof(struct Type2__one_name, _asn_ctx),
	asn_MAP_one_name_tag2el_2,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_one_name_2 = {
	"one-name",
	"one-name",
	&asn_OP_SEQUENCE,
	asn_DEF_one_name_tags_2,
	sizeof(asn_DEF_one_name_tags_2)
		/sizeof(asn_DEF_one_name_tags_2[0]), /* 1 */
	asn_DEF_one_name_tags_2,	/* Same as above */
	sizeof(asn_DEF_one_name_tags_2)
		/sizeof(asn_DEF_one_name_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_one_name_2,
	1,	/* Elements count */
	&asn_SPC_one_name_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_another_name_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type2__two_name__another_name, a),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_a_constr_9, &asn_PER_memb_a_constr_9,  memb_a_constraint_8 },
		0, 0, /* No default value */
		"a"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Type2__two_name__another_name, b),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b"
		},
};
static const ber_tlv_tag_t asn_DEF_another_name_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_another_name_tag2el_8[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* b */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 0 } /* a */
};
static asn_SEQUENCE_specifics_t asn_SPC_another_name_specs_8 = {
	sizeof(struct Type2__two_name__another_name),
	offsetof(struct Type2__two_name__another_name, _asn_ctx),
	asn_MAP_another_name_tag2el_8,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_another_name_8 = {
	"another-name",
	"another-name",
	&asn_OP_SEQUENCE,
	asn_DEF_another_name_tags_8,
	sizeof(asn_DEF_another_name_tags_8)
		/sizeof(asn_DEF_another_name_tags_8[0]), /* 1 */
	asn_DEF_another_name_tags_8,	/* Same as above */
	sizeof(asn_DEF_another_name_tags_8)
		/sizeof(asn_DEF_another_name_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_another_name_8,
	2,	/* Elements count */
	&asn_SPC_another_name_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_two_name_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type2__two_name, another_name),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_another_name_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"another-name"
		},
};
static const ber_tlv_tag_t asn_DEF_two_name_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_two_name_tag2el_7[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* another-name */
};
static const uint8_t asn_MAP_two_name_mmap_7[(1 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7)
};
static 
asn_SET_specifics_t asn_SPC_two_name_specs_7 = {
	sizeof(struct Type2__two_name),
	offsetof(struct Type2__two_name, _asn_ctx),
	offsetof(struct Type2__two_name, _presence_map),
	asn_MAP_two_name_tag2el_7,
	1,	/* Count of tags in the map */
	asn_MAP_two_name_tag2el_7,	/* Same as above */
	1,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(const unsigned int *)asn_MAP_two_name_mmap_7	/* Mandatory elements map */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_two_name_7 = {
	"two-name",
	"two-name",
	&asn_OP_SET,
	asn_DEF_two_name_tags_7,
	sizeof(asn_DEF_two_name_tags_7)
		/sizeof(asn_DEF_two_name_tags_7[0]), /* 1 */
	asn_DEF_two_name_tags_7,	/* Same as above */
	sizeof(asn_DEF_two_name_tags_7)
		/sizeof(asn_DEF_two_name_tags_7[0]), /* 1 */
	{ 0, 0, SET_constraint },
	asn_MBR_two_name_7,
	1,	/* Elements count */
	&asn_SPC_two_name_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Type2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type2, choice.one_name),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_one_name_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"one-name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Type2, choice.two_name),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_two_name_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"two-name"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Type2_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* one-name */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 1, 0, 0 } /* two-name */
};
asn_CHOICE_specifics_t asn_SPC_Type2_specs_1 = {
	sizeof(struct Type2),
	offsetof(struct Type2, _asn_ctx),
	offsetof(struct Type2, present),
	sizeof(((struct Type2 *)0)->present),
	asn_MAP_Type2_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Type2 = {
	"Type2",
	"Type2",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Type2_constr_1, &asn_PER_type_Type2_constr_1, CHOICE_constraint },
	asn_MBR_Type2_1,
	2,	/* Elements count */
	&asn_SPC_Type2_specs_1	/* Additional specs */
};

