/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSetAndUntaggedChoice"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/35-set-choice-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "OID.h"

static asn_oer_constraints_t asn_OER_type_OID_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_OID_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_OID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OID, choice.oid),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"oid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OID, choice.r_oid),
		(ASN_TAG_CLASS_UNIVERSAL | (13 << 2)),
		0,
		&asn_DEF_RELATIVE_OID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r-oid"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_OID_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* oid */
    { (ASN_TAG_CLASS_UNIVERSAL | (13 << 2)), 1, 0, 0 } /* r-oid */
};
asn_CHOICE_specifics_t asn_SPC_OID_specs_1 = {
	sizeof(struct OID),
	offsetof(struct OID, _asn_ctx),
	offsetof(struct OID, present),
	sizeof(((struct OID *)0)->present),
	asn_MAP_OID_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_OID = {
	"OID",
	"OID",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_OID_constr_1, &asn_PER_type_OID_constr_1, CHOICE_constraint },
	asn_MBR_OID_1,
	2,	/* Elements count */
	&asn_SPC_OID_specs_1	/* Additional specs */
};

