/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSetAndUntaggedChoice"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/35-set-choice-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "T.h"

static asn_oer_constraints_t asn_OER_type_b_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_b_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_b_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct b, choice.b1),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct b, choice.b2),
		(ASN_TAG_CLASS_UNIVERSAL | (7 << 2)),
		0,
		&asn_DEF_ObjectDescriptor,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct b, choice.b3),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Choice,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b3"
		},
};
static const unsigned asn_MAP_b_to_canonical_3[] = { 2, 1, 0 };
static const unsigned asn_MAP_b_from_canonical_3[] = { 2, 1, 0 };
static const asn_TYPE_tag2member_t asn_MAP_b_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* ch-b */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* ch-a */
    { (ASN_TAG_CLASS_UNIVERSAL | (7 << 2)), 1, 0, 0 }, /* b2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 } /* b1 */
};
static asn_CHOICE_specifics_t asn_SPC_b_specs_3 = {
	sizeof(struct b),
	offsetof(struct b, _asn_ctx),
	offsetof(struct b, present),
	sizeof(((struct b *)0)->present),
	asn_MAP_b_tag2el_3,
	4,	/* Count of tags in the map */
	asn_MAP_b_to_canonical_3,
	asn_MAP_b_from_canonical_3,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_b_3 = {
	"b",
	"b",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_b_constr_3, &asn_PER_type_b_constr_3, CHOICE_constraint },
	asn_MBR_b_3,
	3,	/* Elements count */
	&asn_SPC_b_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_T_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct T, a),
		(ASN_TAG_CLASS_UNIVERSAL | (18 << 2)),
		0,
		&asn_DEF_NumericString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"a"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct T, b),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_b_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct T, c),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"c"
		},
	{ ATF_POINTER, 1, offsetof(struct T, d),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_OID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"d"
		},
};
static const ber_tlv_tag_t asn_DEF_T_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_T_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, 0, 0 }, /* c */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* ch-b */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* ch-a */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 3, 0, 0 }, /* oid */
    { (ASN_TAG_CLASS_UNIVERSAL | (7 << 2)), 1, 0, 0 }, /* b2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (13 << 2)), 3, 0, 0 }, /* r-oid */
    { (ASN_TAG_CLASS_UNIVERSAL | (18 << 2)), 0, 0, 0 }, /* a */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 1, 0, 0 } /* b1 */
};
static const asn_TYPE_tag2member_t asn_MAP_T_tag2el_cxer_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, 0, 0 }, /* c */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* ch-b */
    { (ASN_TAG_CLASS_UNIVERSAL | (18 << 2)), 0, 0, 0 }, /* a */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 3, 0, 0 } /* oid */
};
static const uint8_t asn_MAP_T_mmap_1[(4 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (1 << 6) | (1 << 5) | (0 << 4)
};
static 
asn_SET_specifics_t asn_SPC_T_specs_1 = {
	sizeof(struct T),
	offsetof(struct T, _asn_ctx),
	offsetof(struct T, _presence_map),
	asn_MAP_T_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_T_tag2el_cxer_1,
	4,	/* Count of tags in the CXER map */
	1,	/* Whether extensible */
	(const unsigned int *)asn_MAP_T_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_T = {
	"T",
	"T",
	&asn_OP_SET,
	asn_DEF_T_tags_1,
	sizeof(asn_DEF_T_tags_1)
		/sizeof(asn_DEF_T_tags_1[0]), /* 1 */
	asn_DEF_T_tags_1,	/* Same as above */
	sizeof(asn_DEF_T_tags_1)
		/sizeof(asn_DEF_T_tags_1[0]), /* 1 */
	{ 0, 0, SET_constraint },
	asn_MBR_T_1,
	4,	/* Elements count */
	&asn_SPC_T_specs_1	/* Additional specs */
};

