/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleNestedConstraintsCheck"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/50-constraint-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_Int4_H_
#define	_Int4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int3.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Int4 */
typedef Int3_t	 Int4_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Int4_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Int4;
asn_struct_free_f Int4_free;
asn_struct_print_f Int4_print;
asn_constr_check_f Int4_constraint;
ber_type_decoder_f Int4_decode_ber;
der_type_encoder_f Int4_encode_der;
xer_type_decoder_f Int4_decode_xer;
xer_type_encoder_f Int4_encode_xer;
oer_type_decoder_f Int4_decode_oer;
oer_type_encoder_f Int4_encode_oer;
per_type_decoder_f Int4_decode_uper;
per_type_encoder_f Int4_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Int4_H_ */
#include <asn_internal.h>
