/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleNestedConstraintsCheck"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/50-constraint-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_PER_Visible_2_H_
#define	_PER_Visible_2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PER-Visible.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PER-Visible-2 */
typedef PER_Visible_t	 PER_Visible_2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PER_Visible_2;
asn_struct_free_f PER_Visible_2_free;
asn_struct_print_f PER_Visible_2_print;
asn_constr_check_f PER_Visible_2_constraint;
ber_type_decoder_f PER_Visible_2_decode_ber;
der_type_encoder_f PER_Visible_2_encode_der;
xer_type_decoder_f PER_Visible_2_decode_xer;
xer_type_encoder_f PER_Visible_2_encode_xer;
oer_type_decoder_f PER_Visible_2_decode_oer;
oer_type_encoder_f PER_Visible_2_encode_oer;
per_type_decoder_f PER_Visible_2_decode_uper;
per_type_encoder_f PER_Visible_2_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PER_Visible_2_H_ */
#include <asn_internal.h>
