/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "../pdu_spec.asn"
 */

#include "AComplexType.h"

static int
memb_clockTicks_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65536)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_clockTicks_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..65536) */,
	-1};
static asn_per_constraints_t asn_PER_memb_clockTicks_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 17, -1,  0,  65536 }	/* (0..65536) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_intSequence_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_intSequence_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_intSequence_specs_3 = {
	sizeof(struct intSequence),
	offsetof(struct intSequence, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_intSequence_3 = {
	"intSequence",
	"intSequence",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_intSequence_tags_3,
	sizeof(asn_DEF_intSequence_tags_3)
		/sizeof(asn_DEF_intSequence_tags_3[0]), /* 1 */
	asn_DEF_intSequence_tags_3,	/* Same as above */
	sizeof(asn_DEF_intSequence_tags_3)
		/sizeof(asn_DEF_intSequence_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_intSequence_3,
	1,	/* Single element */
	&asn_SPC_intSequence_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_AComplexType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AComplexType, clockTicks),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_clockTicks_constr_2, &asn_PER_memb_clockTicks_constr_2,  memb_clockTicks_constraint_1 },
		0, 0, /* No default value */
		"clockTicks"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AComplexType, intSequence),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_intSequence_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"intSequence"
		},
};
static const ber_tlv_tag_t asn_DEF_AComplexType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AComplexType_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* clockTicks */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* intSequence */
};
asn_SEQUENCE_specifics_t asn_SPC_AComplexType_specs_1 = {
	sizeof(struct AComplexType),
	offsetof(struct AComplexType, _asn_ctx),
	asn_MAP_AComplexType_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AComplexType = {
	"AComplexType",
	"AComplexType",
	&asn_OP_SEQUENCE,
	asn_DEF_AComplexType_tags_1,
	sizeof(asn_DEF_AComplexType_tags_1)
		/sizeof(asn_DEF_AComplexType_tags_1[0]), /* 1 */
	asn_DEF_AComplexType_tags_1,	/* Same as above */
	sizeof(asn_DEF_AComplexType_tags_1)
		/sizeof(asn_DEF_AComplexType_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AComplexType_1,
	2,	/* Elements count */
	&asn_SPC_AComplexType_specs_1	/* Additional specs */
};

