/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "../pdu_spec.asn"
 */

#ifndef	_Cell_H_
#define	_Cell_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <OCTET_STRING.h>
#include "AComplexType.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Cell_PR {
	Cell_PR_NOTHING,	/* No components present */
	Cell_PR_intVal,
	Cell_PR_boolVal,
	Cell_PR_name,
	Cell_PR_message
} Cell_PR;

/* Cell */
typedef struct Cell {
	Cell_PR present;
	union Cell_u {
		long	 intVal;
		BOOLEAN_t	 boolVal;
		OCTET_STRING_t	 name;
		AComplexType_t	 message;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Cell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cell;
extern asn_CHOICE_specifics_t asn_SPC_Cell_specs_1;
extern asn_TYPE_member_t asn_MBR_Cell_1[4];
extern asn_per_constraints_t asn_PER_type_Cell_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Cell_H_ */
#include <asn_internal.h>
