/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "../pdu_spec.asn"
 */

#include "Cell.h"

static int
memb_intVal_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_intVal_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..4) */,
	-1};
static asn_per_constraints_t asn_PER_memb_intVal_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_Cell_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Cell_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Cell_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Cell, choice.intVal),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_intVal_constr_2, &asn_PER_memb_intVal_constr_2,  memb_intVal_constraint_1 },
		0, 0, /* No default value */
		"intVal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Cell, choice.boolVal),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"boolVal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Cell, choice.name),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Cell, choice.message),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AComplexType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"message"
		},
};
static const unsigned asn_MAP_Cell_to_canonical_1[] = { 1, 0, 2, 3 };
static const unsigned asn_MAP_Cell_from_canonical_1[] = { 1, 0, 2, 3 };
static const asn_TYPE_tag2member_t asn_MAP_Cell_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 1, 0, 0 }, /* boolVal */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* intVal */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* name */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 } /* message */
};
asn_CHOICE_specifics_t asn_SPC_Cell_specs_1 = {
	sizeof(struct Cell),
	offsetof(struct Cell, _asn_ctx),
	offsetof(struct Cell, present),
	sizeof(((struct Cell *)0)->present),
	asn_MAP_Cell_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Cell_to_canonical_1,
	asn_MAP_Cell_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Cell = {
	"Cell",
	"Cell",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Cell_constr_1, &asn_PER_type_Cell_constr_1, CHOICE_constraint },
	asn_MBR_Cell_1,
	4,	/* Elements count */
	&asn_SPC_Cell_specs_1	/* Additional specs */
};

