/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleCircularReferences"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/92-circular-loops-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_Set_H_
#define	_Set_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Set;
struct Sequence;

/* Forward definitions */
typedef struct Member {
	long	 Int;
	struct Set	*set;
	struct Sequence	*seq;
	struct Set	*set2	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct Set	*set3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Member;

/* Set */
typedef struct Set {
	A_SET_OF(Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Set_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Set;
extern asn_SET_OF_specifics_t asn_SPC_Set_specs_1;
extern asn_TYPE_member_t asn_MBR_Set_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Set.h"
#include "Sequence.h"

#endif	/* _Set_H_ */
#include <asn_internal.h>
