/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleCircularReferences"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/92-circular-loops-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_TypeRef_H_
#define	_TypeRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Sequence.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TypeRef */
typedef Sequence_t	 TypeRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TypeRef;
asn_struct_free_f TypeRef_free;
asn_struct_print_f TypeRef_print;
asn_constr_check_f TypeRef_constraint;
ber_type_decoder_f TypeRef_decode_ber;
der_type_encoder_f TypeRef_encode_der;
xer_type_decoder_f TypeRef_decode_xer;
xer_type_encoder_f TypeRef_encode_xer;
oer_type_decoder_f TypeRef_decode_oer;
oer_type_encoder_f TypeRef_encode_oer;
per_type_decoder_f TypeRef_decode_uper;
per_type_encoder_f TypeRef_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TypeRef_H_ */
#include <asn_internal.h>
