/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Enum1;
extern struct asn_TYPE_descriptor_s asn_DEF_Enum2;
extern struct asn_TYPE_descriptor_s asn_DEF_Enum3;
extern struct asn_TYPE_descriptor_s asn_DEF_Enum4;
extern struct asn_TYPE_descriptor_s asn_DEF_Enum5;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ModuleTestEnum1 in /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/03-enum-OK.asn1 */
	&asn_DEF_Enum1,	
	&asn_DEF_Enum2,	
	&asn_DEF_Enum3,	
	&asn_DEF_Enum4,	
	&asn_DEF_Enum5,	
	0
};

