/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMiscComplex"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/33-misc-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "Label2.h"

/*
 * This type is implemented using Label,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_Label2_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (12 << 2))
};
static const ber_tlv_tag_t asn_DEF_Label2_all_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (12 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Label2 = {
	"Label2",
	"Label2",
	&asn_OP_UTF8String,
	asn_DEF_Label2_tags_1,
	sizeof(asn_DEF_Label2_tags_1)
		/sizeof(asn_DEF_Label2_tags_1[0]), /* 2 */
	asn_DEF_Label2_all_tags_1,
	sizeof(asn_DEF_Label2_all_tags_1)
		/sizeof(asn_DEF_Label2_all_tags_1[0]), /* 3 */
	{ 0, 0, UTF8String_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

