/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMiscComplex"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/33-misc-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_T2_H_
#define	_T2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Label2.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* T2 */
typedef struct T2 {
	Label2_t	 l;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T2;
extern asn_SEQUENCE_specifics_t asn_SPC_T2_specs_1;
extern asn_TYPE_member_t asn_MBR_T2_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _T2_H_ */
#include <asn_internal.h>
