/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_SeqWithNestedSOS;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ModuleTestSequenceOfSequenceNested in /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/158-sequence-of-sequence-nested-OK.asn1 */
	&asn_DEF_SeqWithNestedSOS,	
	0
};

