/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSequenceOfSequenceNested"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/158-sequence-of-sequence-nested-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -fcompound-names`
 */

#include "SeqWithNestedSOS.h"

static asn_TYPE_member_t asn_MBR_Member_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SeqWithNestedSOS__sos__Member__nested_sos__Member, nested_string),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nested-string"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 } /* nested-string */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_7 = {
	sizeof(struct SeqWithNestedSOS__sos__Member__nested_sos__Member),
	offsetof(struct SeqWithNestedSOS__sos__Member__nested_sos__Member, _asn_ctx),
	asn_MAP_Member_tag2el_7,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_7 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_7,
	sizeof(asn_DEF_Member_tags_7)
		/sizeof(asn_DEF_Member_tags_7[0]), /* 1 */
	asn_DEF_Member_tags_7,	/* Same as above */
	sizeof(asn_DEF_Member_tags_7)
		/sizeof(asn_DEF_Member_tags_7[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_7,
	1,	/* Elements count */
	&asn_SPC_Member_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_nested_sos_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_nested_sos_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nested_sos_specs_6 = {
	sizeof(struct SeqWithNestedSOS__sos__Member__nested_sos),
	offsetof(struct SeqWithNestedSOS__sos__Member__nested_sos, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nested_sos_6 = {
	"nested-sos",
	"nested-sos",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_nested_sos_tags_6,
	sizeof(asn_DEF_nested_sos_tags_6)
		/sizeof(asn_DEF_nested_sos_tags_6[0]) - 1, /* 1 */
	asn_DEF_nested_sos_tags_6,	/* Same as above */
	sizeof(asn_DEF_nested_sos_tags_6)
		/sizeof(asn_DEF_nested_sos_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_nested_sos_6,
	1,	/* Single element */
	&asn_SPC_nested_sos_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SeqWithNestedSOS__sos__Member, anotherString),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"anotherString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SeqWithNestedSOS__sos__Member, nested_sos),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_nested_sos_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nested-sos"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* anotherString */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 } /* nested-sos */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_4 = {
	sizeof(struct SeqWithNestedSOS__sos__Member),
	offsetof(struct SeqWithNestedSOS__sos__Member, _asn_ctx),
	asn_MAP_Member_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_4 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_4,
	sizeof(asn_DEF_Member_tags_4)
		/sizeof(asn_DEF_Member_tags_4[0]), /* 1 */
	asn_DEF_Member_tags_4,	/* Same as above */
	sizeof(asn_DEF_Member_tags_4)
		/sizeof(asn_DEF_Member_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_4,
	2,	/* Elements count */
	&asn_SPC_Member_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_sos_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_sos_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sos_specs_3 = {
	sizeof(struct SeqWithNestedSOS__sos),
	offsetof(struct SeqWithNestedSOS__sos, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sos_3 = {
	"sos",
	"sos",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_sos_tags_3,
	sizeof(asn_DEF_sos_tags_3)
		/sizeof(asn_DEF_sos_tags_3[0]) - 1, /* 1 */
	asn_DEF_sos_tags_3,	/* Same as above */
	sizeof(asn_DEF_sos_tags_3)
		/sizeof(asn_DEF_sos_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_sos_3,
	1,	/* Single element */
	&asn_SPC_sos_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SeqWithNestedSOS_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SeqWithNestedSOS, someString),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"someString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SeqWithNestedSOS, sos),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_sos_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sos"
		},
};
static const ber_tlv_tag_t asn_DEF_SeqWithNestedSOS_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SeqWithNestedSOS_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* someString */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sos */
};
static asn_SEQUENCE_specifics_t asn_SPC_SeqWithNestedSOS_specs_1 = {
	sizeof(struct SeqWithNestedSOS),
	offsetof(struct SeqWithNestedSOS, _asn_ctx),
	asn_MAP_SeqWithNestedSOS_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SeqWithNestedSOS = {
	"SeqWithNestedSOS",
	"SeqWithNestedSOS",
	&asn_OP_SEQUENCE,
	asn_DEF_SeqWithNestedSOS_tags_1,
	sizeof(asn_DEF_SeqWithNestedSOS_tags_1)
		/sizeof(asn_DEF_SeqWithNestedSOS_tags_1[0]), /* 1 */
	asn_DEF_SeqWithNestedSOS_tags_1,	/* Same as above */
	sizeof(asn_DEF_SeqWithNestedSOS_tags_1)
		/sizeof(asn_DEF_SeqWithNestedSOS_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SeqWithNestedSOS_1,
	2,	/* Elements count */
	&asn_SPC_SeqWithNestedSOS_specs_1	/* Additional specs */
};

