/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestANYSyntax"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/62-any-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#include "T.h"

static asn_oer_constraints_t asn_OER_type_T_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_T_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_T_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct T, choice.s1),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_T1_ext,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"s1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct T, choice.s2),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		0,
		&asn_DEF_T2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"s2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct T, choice.s3),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_T3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"s3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct T, choice.s4),
		(ASN_TAG_CLASS_CONTEXT | (53 << 2)),
		0,
		&asn_DEF_T4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"s4"
		},
};
static const unsigned asn_MAP_T_to_canonical_1[] = { 0, 2, 1, 3 };
static const unsigned asn_MAP_T_from_canonical_1[] = { 0, 2, 1, 3 };
static const asn_TYPE_tag2member_t asn_MAP_T_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* s1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 2, 0, 0 }, /* s3 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 1, 0, 0 }, /* s2 */
    { (ASN_TAG_CLASS_CONTEXT | (53 << 2)), 3, 0, 0 } /* s4 */
};
static asn_CHOICE_specifics_t asn_SPC_T_specs_1 = {
	sizeof(struct T),
	offsetof(struct T, _asn_ctx),
	offsetof(struct T, present),
	sizeof(((struct T *)0)->present),
	asn_MAP_T_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_T_to_canonical_1,
	asn_MAP_T_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_T = {
	"T",
	"T",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_T_constr_1, &asn_PER_type_T_constr_1, CHOICE_constraint },
	asn_MBR_T_1,
	4,	/* Elements count */
	&asn_SPC_T_specs_1	/* Additional specs */
};

