/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestANYSyntax"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/62-any-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_T1_ext_H_
#define	_T1_ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* T1-ext */
typedef struct T1_ext {
	long	*i	/* OPTIONAL */;
	ANY_t	 any;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T1_ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T1_ext;
extern asn_SEQUENCE_specifics_t asn_SPC_T1_ext_specs_1;
extern asn_TYPE_member_t asn_MBR_T1_ext_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _T1_ext_H_ */
#include <asn_internal.h>
