/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestANYSyntax"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/62-any-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_T4_H_
#define	_T4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum T4_PR {
	T4_PR_NOTHING,	/* No components present */
	T4_PR_m1
} T4_PR;

/* T4 */
typedef struct T4 {
	T4_PR present;
	union T4_u {
		OCTET_STRING_t	 m1;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T4;
extern asn_CHOICE_specifics_t asn_SPC_T4_specs_1;
extern asn_TYPE_member_t asn_MBR_T4_1[1];
extern asn_per_constraints_t asn_PER_type_T4_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _T4_H_ */
#include <asn_internal.h>
