/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSetOfSimple"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/31-set-of-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -fwide-types`
 */

#include "Forest.h"

asn_TYPE_member_t asn_MBR_Forest_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Tree,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_Forest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
asn_SET_OF_specifics_t asn_SPC_Forest_specs_1 = {
	sizeof(struct Forest),
	offsetof(struct Forest, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_Forest = {
	"Forest",
	"Forest",
	&asn_OP_SET_OF,
	asn_DEF_Forest_tags_1,
	sizeof(asn_DEF_Forest_tags_1)
		/sizeof(asn_DEF_Forest_tags_1[0]), /* 1 */
	asn_DEF_Forest_tags_1,	/* Same as above */
	sizeof(asn_DEF_Forest_tags_1)
		/sizeof(asn_DEF_Forest_tags_1[0]), /* 1 */
	{ 0, 0, SET_OF_constraint },
	asn_MBR_Forest_1,
	1,	/* Single element */
	&asn_SPC_Forest_specs_1	/* Additional specs */
};

