/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSetOfSimple"
 * 	found in "/Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/tests/tests-asn1c-compiler/31-set-of-OK.asn1"
 * 	`asn1c -S /Users/tasospsomadopoulos/Documents/asn1_sample/asn1c/skeletons -flink-skeletons -Wdebug-compiler -fwide-types`
 */

#include "Tree.h"

asn_TYPE_member_t asn_MBR_Tree_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Tree, height),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"height"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Tree, width),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"width"
		},
};
static const ber_tlv_tag_t asn_DEF_Tree_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Tree_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* height */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* width */
};
asn_SEQUENCE_specifics_t asn_SPC_Tree_specs_1 = {
	sizeof(struct Tree),
	offsetof(struct Tree, _asn_ctx),
	asn_MAP_Tree_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Tree = {
	"Tree",
	"Tree",
	&asn_OP_SEQUENCE,
	asn_DEF_Tree_tags_1,
	sizeof(asn_DEF_Tree_tags_1)
		/sizeof(asn_DEF_Tree_tags_1[0]), /* 1 */
	asn_DEF_Tree_tags_1,	/* Same as above */
	sizeof(asn_DEF_Tree_tags_1)
		/sizeof(asn_DEF_Tree_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Tree_1,
	2,	/* Elements count */
	&asn_SPC_Tree_specs_1	/* Additional specs */
};

