/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "../asn/pdu_spec.asn"
 */

#ifndef	_AComplexType_H_
#define	_AComplexType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AComplexType */
typedef struct AComplexType {
	long	 clockTicks;
	struct intSequence {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} intSequence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AComplexType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AComplexType;
extern asn_SEQUENCE_specifics_t asn_SPC_AComplexType_specs_1;
extern asn_TYPE_member_t asn_MBR_AComplexType_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AComplexType_H_ */
#include <asn_internal.h>
